# Generated by Django 3.2.18 on 2023-05-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroptions',
            name='bias_hours_explanation',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
