# Generated by Django 3.2.18 on 2023-05-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0003_biashours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroptions',
            name='bias_hours',
        ),
        migrations.RemoveField(
            model_name='useroptions',
            name='bias_hours_explanation',
        ),
    ]
