# Generated by Django 3.2.18 on 2023-05-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0004_auto_20230506_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biashours',
            options={'ordering': ('approved',)},
        ),
    ]
