# Generated by Django 3.2.18 on 2023-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0005_alter_biashours_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biashours',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
