# Generated by Django 3.2.18 on 2023-06-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0007_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobrating',
            name='rating_str',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='rating_str'),
        ),
    ]
