# Generated by Django 3.2.18 on 2023-06-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0008_userjobrating_rating_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjobrating',
            name='rating_str',
        ),
    ]
