# Generated by Django 3.2.16 on 2022-12-15 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shiftplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True, verbose_name='shiftplan_name')),
                ('time_format', models.CharField(default='hourly', max_length=50, verbose_name='time_format')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('shiftplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.shiftplan')),
            ],
        ),
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='jobtype name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('default_rating', models.IntegerField(default=3)),
                ('shiftplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.shiftplan')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='job begin')),
                ('end', models.DateTimeField(verbose_name='job end')),
                ('rating', models.IntegerField(default=3, verbose_name='rating')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.jobtype')),
            ],
        ),
    ]
