# Generated by Django 4.1.2 on 2022-10-29 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='day name')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='jobtype name')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='job begin')),
                ('end', models.DateTimeField(verbose_name='job end')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.day')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.jobtype')),
            ],
        ),
    ]
