# Generated by Django 3.2.18 on 2023-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='job',
            name='end',
        ),
        migrations.AddField(
            model_name='job',
            name='begin_date',
            field=models.DateField(null=True, verbose_name='job begin date'),
        ),
        migrations.AddField(
            model_name='job',
            name='begin_time',
            field=models.TimeField(null=True, verbose_name='job begin time'),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(null=True, verbose_name='job end date'),
        ),
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='job end time'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rating',
            field=models.IntegerField(verbose_name='rating'),
        ),
    ]
