# Generated by Django 4.1.3 on 2022-11-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='day',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobtype',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Jobtype',
        ),
    ]
