# Generated by Django 4.1.3 on 2022-11-03 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defs', '0002_remove_job_day_remove_job_jobtype_delete_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='day name')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='subgroup name')),
            ],
        ),
        migrations.CreateModel(
            name='Shiftplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.subgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='jobtype name')),
                ('shiftplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.shiftplan')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.subgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='job begin')),
                ('end', models.DateTimeField(verbose_name='job end')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.day')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.jobtype')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='shiftplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.shiftplan'),
        ),
    ]
