# Generated by Django 3.2.18 on 2023-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defs', '0002_auto_20230329_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='begin_date',
            field=models.DateField(verbose_name='job begin date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='begin_time',
            field=models.TimeField(verbose_name='job begin time'),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(verbose_name='job end date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_time',
            field=models.TimeField(verbose_name='job end time'),
        ),
    ]
