# Generated by Django 4.1.3 on 2022-11-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defs', '0004_remove_job_day_remove_jobtype_subgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftplan',
            name='time_format',
            field=models.CharField(default='hourly', max_length=50, verbose_name='time_format'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='shiftplan_name'),
        ),
    ]
