# Generated by Django 3.2.18 on 2023-03-30 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('defs', '0005_auto_20230330_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
