# Generated by Django 3.2.18 on 2023-05-26 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sols', '0003_userjobassignment_solution_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionrun',
            name='final',
        ),
        migrations.RemoveField(
            model_name='userjobassignment',
            name='solution_run',
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(default=False)),
                ('solution_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sols.solutionrun')),
            ],
        ),
    ]
