# Generated by Django 3.2.18 on 2023-05-26 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sols', '0004_auto_20230526_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobassignment',
            name='solution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sols.solution'),
            preserve_default=False,
        ),
    ]
