# Generated by Django 3.2.18 on 2023-05-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sols', '0005_userjobassignment_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionrun',
            name='timestamp',
            field=models.DateTimeField(unique=True, verbose_name='solution run timestamp'),
        ),
    ]
