# Generated by Django 3.2.18 on 2023-06-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sols', '0006_alter_solutionrun_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrun',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
