# Generated by Django 3.2.18 on 2023-06-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='cand_list_name')),
                ('file', models.FileField(upload_to='candidates_files')),
            ],
        ),
        migrations.CreateModel(
            name='UserCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='cand username')),
                ('forename', models.CharField(blank=True, max_length=200, null=True, verbose_name='cand forename')),
                ('surname', models.CharField(blank=True, max_length=200, null=True, verbose_name='cand surname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='cand email')),
            ],
        ),
    ]
