# Generated by Django 3.2.18 on 2023-03-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobrating',
            name='rating',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
