# Generated by Django 3.2.18 on 2023-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0002_alter_userjobrating_rating'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userjobrating',
            index=models.Index(fields=['user', 'job'], name='prefs_userj_user_id_3c8bfe_idx'),
        ),
    ]
