# Generated by Django 3.2.18 on 2023-04-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
