# Generated by Django 3.2.18 on 2023-05-02 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='crew_name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='jobtype name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('default_rating', models.IntegerField(default=3)),
                ('restricted_to_subcrew', models.BooleanField(default=False)),
                ('subcrew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='defs.subcrew')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(verbose_name='job begin date')),
                ('end_date', models.DateField(verbose_name='job end date')),
                ('begin_time', models.TimeField(verbose_name='job begin time')),
                ('end_time', models.TimeField(verbose_name='job end time')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='rating')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defs.jobtype')),
            ],
        ),
    ]
