# Generated by Django 3.2.18 on 2023-05-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defs', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='priority',
            field=models.IntegerField(default=3),
        ),
    ]
