# Generated by Django 3.2.18 on 2023-05-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defs', '0004_jobtype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='priority'),
        ),
    ]
