# Generated by Django 3.2.18 on 2023-05-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defs', '0005_job_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='mode_name')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='mode_description')),
            ],
        ),
        migrations.CreateModel(
            name='Shiftplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='shiftplan_name')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='defs.mode')),
            ],
        ),
    ]
