# Generated by Django 3.2.18 on 2023-05-23 22:27

from django.db import migrations

"""Modes Definition."""

MODES = [
    {
        "name": "assign_every_job",
        "description": """
        Regardless of its priority, each job is assigned to a user.
        The workload is not user selectable.
        Each user can propose bias working hours.
        """
    },
    {
        "name": "non_prioritized",
        "description": """
        Assign as many jobs as possible without priorities.
        The workload is user selectable.
        The algorithm assignes as many jobs as possible, but without exceeding each users workload.
        Priorities and bias hours are not considered.
        """
    },
    {
        "name": "prioritized",
        "description": """
        Assign as many jobs as possible with priorities.
        The workload is user selectable.
        The algorithm assignes as many jobs as possible, but without exceeding each users workload. Jobs with higher priorities are assigned more likely.
        Bias hours are not considered.
        """
    }
]

# print(MODES)

def create_modes(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Mode = apps.get_model("defs", "Mode")
    for m in MODES:
        new_mode = Mode(name=m["name"], description=m["description"].strip())
        new_mode.save()

class Migration(migrations.Migration):

    dependencies = [
        ('defs', '0006_mode_shiftplan'),
    ]

    operations = [
        migrations.RunPython(create_modes),
    ]
